# Значения по умолчанию для чарта simple-app.
# Их можно переопределить в ArgoCD Application (в блоке helm.values / valueFiles)

replicaCount: 2

image:
  repository: bridgetstephani/simple-app   # замените на свой образ
  tag: "1.0.0"
  pullPolicy: IfNotPresent

# Переменные окружения, которые пробросим в приложение
env:
  greeting: "Привет из Helm values!"
  appVersion: "v1"

service:
  type: ClusterIP
  port: 80          # порт сервиса
  targetPort: 8080  # порт, который слушает приложение (main.py)

ingress:
  enabled: true
  className: nginx
  host: simple-app.158.160.219.233.sslip.io
  path: /

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

probes:
  livenessPath: /healthz
  readinessPath: /healthz
