{{- if .Values.traefik.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1  # Для старых версий Traefik (v2) может потребоваться traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "cnyrub-predictor.fullname" . }}
  labels:
    {{- include "cnyrub-predictor.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.traefik.ingressRoute.entryPoint | default "web" }}
  routes:
    - match: Host(`{{ .Values.traefik.ingressRoute.host }}`)
      kind: Rule
      services:
        - name: {{ include "cnyrub-predictor.fullname" . }}
          port: {{ .Values.service.port }} # Убедитесь, что в values.yaml есть секция service.port
{{- if .Values.traefik.ingressRoute.tls }}
  tls:
    secretName: {{ .Values.traefik.ingressRoute.tls.secretName }}
{{- end }}
{{- end }}
