apiVersion: v1
kind: Secret
metadata:
  name: mlflow-basic-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: mlflow
type: Opaque
stringData:
  # Формат строго: имя_пользователя:хеш_пароля
  users: "admin:$apr1$aSRHlGn4$vYmTKUg71k4g5yyZUc8pn."
---
apiVersion: traefik.io/v1alpha1
# Если у вас старая версия Traefik (v2.9 и ниже), используйте: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: mlflow-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: mlflow
spec:
  basicAuth:
    secret: mlflow-basic-auth
    # Опционально: убрать заголовок авторизации из запросов к бэкенду
    removeHeader: true 