{{- if and .Values.mlflow.enabled .Values.mlflow.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "cnyrub-predictor.fullname" . }}-mlflow
  labels:
    {{- include "cnyrub-predictor.labels" . | nindent 4 }}
    app.kubernetes.io/component: mlflow
spec:
  entryPoints:
    - {{ .Values.mlflow.ingress.entryPoint | default "websecure" }}
  routes:
    - match: Host(`{{ .Values.mlflow.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ include "cnyrub-predictor.fullname" . }}-mlflow
          port: {{ .Values.mlflow.port }}
  {{- if .Values.mlflow.ingress.tls.enabled }}
  tls:
    secretName: {{ .Values.mlflow.ingress.tls.secretName }}
  {{- end }}
{{- end }}
